language: node_js
node_js:
- '0.10'
branches:
  only:
  - master
env:
  global:
    secure: c7a+rytQpGIw/rlA3vB6XRctdUujOjHooG0xW4DtyboRdXKcPwhb0oQxoNOq6+1fNUqVj/XimZzLL0YLP3s2znzJCL5XRd7lucbNXCaOp+mZsIgZ9BuN2gQ7r7BKSGIVy6B9F95LpZAj65ciU+E7VEIaTXHdje/1uoXb3K8kNvGNXs7A0Ldaayi3eREyUnmpHcjsx5OmURO343UeOYqq2ZRDkfn2WrANu6LJIDap6JIk4HlC4MJuXOKlpDM+2Wq6eKvi7mFWaH2L9NIpPYofGp+TzYhv3r81pyuRR0iLTdpSNxZwE216sHeM59FJpMrz1GGCAVB7C3+ekBNG4nHqpX6isUbeUd1MWCC/8Xdl+d0zcp2+6VHUP6UPo5qCSD7XoCJ9aDW1ktEPJoAgWYEXRNQH+2Nkq9x8lP+MchbK2qEJk+Ww3vK/9Qkm9cXs2kVMMHyr3YgJWWzP0azp4zAZbYPOZNhdBka5i0FG3Aqq3kv2Df7zXQPuZlorZKIXZdKiaggvXkZsgKRfLT2KtJ2FPPeARVliuXxhe0JRIhmux6NHAPFQC2s3a0V7oG9dGiBjjGZruBrudRmwv3krUcQalFCul56he6YIBoGYl6VMsrQjegk0eYXmn70/TThvyV/5M2cRE2OWyvVmqROzNfQBazgP1+7RIgVYNB5gLe8GU34=
before_install:
- npm install
script: bash travis.sh
